### ISSUE TITLE
Integration with Expo

### ISSUE THREAD

**Issue by ColeTownsend** [approov/quickstart-react-native#35]
Hey team,

Are there any specific actions to integrate with Expo? Usually things with native code either require a [plugin](https://docs.expo.dev/config-plugins/introduction/).

**Comment by richardmtaylor** [comment]
We don't formally support Expo, and we definitely cannot work with Expo Go due to the need for native libraries. But thanks for bringing this to our attention, we are certainly going to bump the priority of getting the plugin configuration defined so that it can be supported in future.

**Comment by ColeTownsend** [comment]
Cool! We're working on implementing in our own app and will let you know how it goes. Expo supports using native modules / things that require native code (like pods) so long as you do what they call a `prebuild`.

**Comment by richardmtaylor** [comment]
Okay great, if you could share what you've done then that would be very helpful to us actually.

**Comment by ColeTownsend** [comment]
`expo install` and then rebuilding the dev (and native) client seems to do the trick!

**Comment by richardmtaylor** [comment]
You mean using "expo install" to install the Approov package, rather than "npm install"?

**Comment by ColeTownsend** [comment]
Yep! That just about covers it as expo install makes sure all pod stuff is synced.

Their build system now allows native code and will compile it!

![Group 1](https://github.com/approov/quickstart-react-native/assets/987654/6ad50272-3945-44c7-8df5-b5e5ab5ac92b)

**Comment by richardmtaylor** [comment]
Okay thanks, have mentioned in the README
